from __future__ import annotations

from typing import Protocol

from domain.models import Session, Turn


class SessionStore(Protocol):
    def create(self, session: Session) -> None: ...
    def append_turn(self, session_id: str, turn: Turn) -> None: ...
    def load(self, session_id: str) -> Session: ...
    def list(self, limit: int = 20) -> list[dict]: ...
    def exists(self, session_id: str) -> bool: ...
